baseURL: "https://main--the-tensor-collective.netlify.app/"
title: The Tensor Collective
theme: PaperMod
metadataformat: "yaml"
languageCode: en-us

params:
  label:
    icon: "/brand/favicon_io/favicon.ico"
    
  homeInfoParams:
    Title: Welcome to the Tensor Collective
    Content: Hello! We're a technical blog for machine learning. We launched in December 2023,
      and we're still getting started. We aim to provide blogs on AI 
      relating technical concepts. We're happy to expand our team, so if you're interested please do reach out.
      Feel free to check out our articles below, the tags tab will have the
      articles by key-word and the categories tab will have the articles by broader topics.
      We hope you enjoy our articles!
  defaultTheme: auto
  
  # General Blog settings
  ShowCodeCopyButtons: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowShareButtons: false
  ShowWordCount: true
  # ShowRssButtonInSectionTermList: true
  description: true

  # Socials
  comments: true
  author: ["Jasper Butcher"]
  socialIcons:
    - name: github
      url: "https://github.com/Ubiquinone-dot"
    - name: linkedin
      url: "https://www.linkedin.com/in/jasper-butcher-a08450207/"
    - name: twitter
      url: ""
    - name: other
      url: ""

  assets:
    # Using: https://favicon.io/favicon-converter/
    favicon: "/brand/favicon_io/favicon.ico"
    favicon16x16:  "/brand/favicon_io/favicon-16x16.png"
    favicon32x32:  "/brand/favicon_io/favicon-32x32.png"
    # apple_touch_icon:  "/brand/favicon_io/apple-touch-icon.png"
    # safari_pinned_tab:  "/brand/favicon_io/safari-pinned-tab.svg"
    # theme_color: "#ffffff"


# MD to HTML settings
markup:
  defaultMarkdownHandler: goldmark
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    style: monokai

menu: 
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: about
      name: About
      url: /about/
      weight: 40
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 50
    # - identifier: graphview
    #   name: Graph View
    #   url: /graphview/
    #   weight: 40  

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
