baseURL: "https://main--the-tensor-collective.netlify.app/"
title: The Tensor Collective
theme: PaperMod
metadataformat: "yaml"
languageCode: en-us

params:
  label:
    icon: "/brand/favicon_io/favicon.ico"
    
  homeInfoParams:
    Title: Welcome to the Tensor Collective
    Content: TTC is a technical blog of mine for machine learning. I launched TTC in December 2023, for
      a few reasons;
      Firstly, I believe there's a place for honest documentation and showcase
      of projects and ideas, in less serious settings than my academic work.
      Secondly, this place serves as a log of some of my notes, writing challenges me
      to be more concise and clear in my thinking.
      Lastly, I often find articles and guides to be devoid of 
      passion for the subject, and I hope to put slightly less focus on rigour
      and more on telling a captivating story with my articles.
      Please do reach out if you have any questions, I hope you enjoy the articles!
  defaultTheme: auto
  
  # General Blog settings
  ShowCodeCopyButtons: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowShareButtons: false
  ShowWordCount: true
  # ShowRssButtonInSectionTermList: true
  description: true

  # Socials
  comments: true
  author: ["Jasper Butcher"]
  socialIcons:
    - name: github
      url: "https://github.com/Ubiquinone-dot"
    - name: linkedin
      url: "https://www.linkedin.com/in/jasper-butcher-a08450207/"
    - name: twitter
      url: ""
    - name: other
      url: ""

  assets:
    # Using: https://favicon.io/favicon-converter/
    favicon: "/assets/favicon.ico"
    favicon16x16:  "/assets/favicon-16x16.png"
    favicon32x32:  "/assets/favicon-32x32.png"
    # apple_touch_icon:  "/brand/favicon_io/apple-touch-icon.png"
    # safari_pinned_tab:  "/brand/favicon_io/safari-pinned-tab.svg"
    # theme_color: "#ffffff"


# MD to HTML settings
markup:
  defaultMarkdownHandler: goldmark
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    style: monokai

menu: 
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    # - identifier: categories
    #   name: Categories
    #   url: /categories/
    #   weight: 20
    # - identifier: tags
    #   name: Tags
    #   url: /tags/
    #   weight: 30
    # - identifier: about
    #   name: About
    #   url: /about/
    #   weight: 40
    # - identifier: archives
    #   name: Archives
    #   url: /archives/
    #   weight: 50
    # - identifier: graphview
    #   name: Graph View
    #   url: /graphview/
    #   weight: 40  

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
